### ISSUE TITLE
About the real-time AVSR model

### ISSUE THREAD

**Issue by csf123123** [mpc001/auto_avsr#19]
Hi ,
    Thanks for sharing your work. May I ask when will the real-time audiovisual pretrained models be likely to be released? 
I download a realtime avsr model from https://download.pytorch.org/torchaudio/tutorial-assets/device_avsr_model.pt .
Then I want to test the eval.py(https://github.com/pytorch/audio/tree/main/examples/avsr/eval.py ). But it was wrong when load the model

**Comment by mpc001** [comment]
Hi @csf123123, we are not allowed to provide the corresponding pretrained model for  [avsr](https://github.com/pytorch/audio/tree/main/examples/avsr) repository due to legal issues. The model you've linked is seperated from the repository. Please note that that model is compatible with torchaudio version 2.0.2.
